# سوال اول 

اولین مرحله اضافه کردن کتابخانه هاست در این قسمت فقط از کتابخانه نامپای استفاده شده است 

In [81]:
import numpy as np

در اولین مرحله باید محیط بازی خود را بسازیم 

برای ساخت محیط بازی خود ابتدا نیاز داریم حرکت را برای عامل تعریف کنیم 

از ان جا که هر خانه که عامل در ان قرار دارد مربعی است و در صورت سوال گفته شده 4 حرکت در هر خانه میتواند انجام دهد بنابراین داریم:

In [82]:
#بالا
up=0
#پایین
down=1
#چپ
left=2
#راست
right=3

در این قسمت دو متغیر را تعریف میکنیم تا در ادامه کد ها راحت باشیم متغیر اول تعداد خانه هایی که عامل میتواند در محیط باشد است و متغیر دوم تعداد حرکت هایی که عامل میتواند در محیط به طور کلی داشته باشد

In [83]:
noS=64 #زمین بازی 8*8 است یعنی به تعداد 64 حالت دارد
noA=4 #تعداد اعمال عامل در محیط که شامل حرکت به بالا، پایین، چپ و راست است

حال باید حالت ها را مشخص کنیم از انجا که گفتیم ما 64 خانه داریم پس یک متغیر تعریف میکنیم که ارایه ای است شامل 64 خانه

In [84]:
S=range(noS) #ارایه ای شامل 64 حالت که عامل میتواند در محیط باشد

از ان جا که در صورت سوال گفته شده ما پاداش همه حرکت ها را صفر در نظر میگیریم و خانه اخر که هدف ماست را فقط 100 در نظر میگیریم بنابراین پاداش برابر 0  تعیین میکنیم

In [85]:
reward =0 # پاداش هر عمل عامل در محیط غیر حالت هدف 0 در نظر گرفته شده است 

حال باید خانه شروع حرکت عامل و خانه هدف عامل را در این زمین 8 در 8 مشخص کنیم 

In [86]:
terminal_state = lambda s: s==24 or s==noS-1 #تعریف خانه شروع و پایان برای عامل 

در این قسمت همانطور که در صورت سوال هم مطرح شده در محیط بعضی خانه ها دیوار است و باید ان ها را مشخص کنیم تا عامل در ان جا قرار نگیرد

In [87]:
wall=[12,26,34,42,46,54,62] #دیوارهایی که در محیط بازی وجود دارد و عامل در این حالات نمیتواند وارد شود

در این قسمت میخواهیم برای عامل محیط را بسازیم و به هر کدام احتمال حرکت عامل را در محیط بدهیم برای این کار باید خانه های اطراف محیط 8 در8 را تعریف کنیم به طوریکه عامل بیشتر از 8 در 8 نتواند جلو برود و در همان محدوده حرکت کند از طرفی هم باید عمل هایی را برای عامل تعریف کنیم که عامل در دیوار ها نتواند وارد شود و بعد حرکت به سمت دیوار در همان ناحیه بماند

یک دیکشنری تعریف میکنیم و برای هر عمل خانه هایی که میتواند برود را مشخص میکنیم

به این صورت که به ازای هر عمل و هر حالت که عامل در ان است 3 مورد را در خروجی نمایش میدهیم اولین حالت بعدی که عامل در ان قرار میگیرد برای مثال اگر عامل در خانه 0 باشد با حرکت به بالا عامب به خانه 8 میرود

دومین مورد احتمال اینکه این حرکت را انجام دهد را تعیین میکنیم و سومین هم پاداشی که از این عمل به دست می اورد را در خروجی نمایش میدهیم 

In [94]:
#ساخت محیط
P=dict()
for s in S: # برای کلیه حالات 
    P[s]=dict()
    # اگر عامل در خانه هدف قرار گیرد به ازای هر عمل حالت بعدی را همان خانه و احتمال رسیدن
    #را 0.25 و پاداش عامل در همان حالت را 100 در نظر بگیرد
    if (terminal_state(s)):  
        P[s][up]=(s,0.25,100) 
        P[s][down]=(s,0.25,100)
        P[s][right]=(s,0.25,100)
        P[s][left]=(s,0.25,100)
    else:# یعنی عامل به هدف نرسیده 
        
    #اگر عامل در 8 خانه انتها به هدف است یعنی در ضلع بالای مربع و عمل بالا رفتن میخواهد انجام دهد
    # حالت بعدی را همان حالت در نظر بگیرد و از مربع 8 در 8 بیرون نرود
        next_s= s if(64-s<=8) else s+8  
        
        #اگر عامل با عمل بالا رفتن به یکی از حالت های دیوار برخورد میکند در همان خانه باقی بماند
        if next_s in wall:
            P[s][up]=(s,0.25,0)
            
        #در غیر این صورت 8 خانه به خانه ای که در ان قرار دارد اضافه شود
        else:
            P[s][up]=(next_s,0.25,reward)
        
    #اگر عامل در 8 خانه ابتدایی است یعنی در ضلع پایین مربع و عمل پایین رفتن میخواهد انجام دهد
    # حالت بعدی را همان حالت در نظر بگیرد و از مربع 8 در 8 بیرون نرود
        next_s= s if(s<8) else s-8
        
        #اگر عامل با عمل پایین رفتن به یکی از حالت های دیوار برخورد میکند در همان خانه باقی بماند
        if next_s in wall:
            P[s][down]=(s,0.25,0)
            
        #در غیر این صورت 8 خانه از خانه ای که در ان قرار دارد کم شود    
        else:
            P[s][down]=(next_s,0.25,reward)
            
    #اگر عامل در خانه های سمت چپی است یعنی در ضلع سمت چپی مربع و عمل چپ رفتن میخواهد انجام دهد
    # حالت بعدی را همان حالت در نظر بگیرد و از مربع 8 در 8 بیرون نرود    
        next_s= s if((s+1)%8==0) else s+1
        
        #اگر عامل با عمل چپ رفتن به یکی از حالت های دیوار برخورد میکند در همان خانه باقی بماند
        if next_s in wall:
            P[s][left]=(s,0.25,0)
            
        #در غیر این صورت 1 خانه از خانه ای که در ان قرار دارد کم شود
        else:
            P[s][left]=(next_s,0.25,reward)
        
    #اگر عامل در خانه های سمت راستی است یعنی در ضلع سمت راست مربع و عمل راست رفتن میخواهد انجام دهد
    # حالت بعدی را همان حالت در نظر بگیرد و از مربع 8 در 8 بیرون نرود
        next_s= s if(s%8==0) else s-1
        
        #اگر عامل با عمل راست رفتن به یکی از حالت های دیوار برخورد میکند در همان خانه باقی بماند
        if next_s in wall:
            P[s][right]=(s,0.25,0)
            
        #در غیر این صورت 1 خانه به خانه ای که در ان قرار دارد اضافه شود
        else:
            P[s][right]=(next_s,0.25,reward)
            
        #در خانه هایی که دیوار در ان قرار دارد صفر در نظر بگیر
for s in S:
    if s in wall:
        P[s][left]=(s,0,0)
        P[s][right]=(s,0,0)
        P[s][down]=(s,0,0)
        P[s][up]=(s,0,0)

In [95]:
P

{0: {0: (8, 0.25, 0), 1: (0, 0.25, 0), 2: (1, 0.25, 0), 3: (0, 0.25, 0)},
 1: {0: (9, 0.25, 0), 1: (1, 0.25, 0), 2: (2, 0.25, 0), 3: (0, 0.25, 0)},
 2: {0: (10, 0.25, 0), 1: (2, 0.25, 0), 2: (3, 0.25, 0), 3: (1, 0.25, 0)},
 3: {0: (11, 0.25, 0), 1: (3, 0.25, 0), 2: (4, 0.25, 0), 3: (2, 0.25, 0)},
 4: {0: (4, 0.25, 0), 1: (4, 0.25, 0), 2: (5, 0.25, 0), 3: (3, 0.25, 0)},
 5: {0: (13, 0.25, 0), 1: (5, 0.25, 0), 2: (6, 0.25, 0), 3: (4, 0.25, 0)},
 6: {0: (14, 0.25, 0), 1: (6, 0.25, 0), 2: (7, 0.25, 0), 3: (5, 0.25, 0)},
 7: {0: (15, 0.25, 0), 1: (7, 0.25, 0), 2: (7, 0.25, 0), 3: (6, 0.25, 0)},
 8: {0: (16, 0.25, 0), 1: (0, 0.25, 0), 2: (9, 0.25, 0), 3: (8, 0.25, 0)},
 9: {0: (17, 0.25, 0), 1: (1, 0.25, 0), 2: (10, 0.25, 0), 3: (8, 0.25, 0)},
 10: {0: (18, 0.25, 0), 1: (2, 0.25, 0), 2: (11, 0.25, 0), 3: (9, 0.25, 0)},
 11: {0: (19, 0.25, 0), 1: (3, 0.25, 0), 2: (11, 0.25, 0), 3: (10, 0.25, 0)},
 12: {0: (12, 0, 0), 1: (12, 0, 0), 2: (12, 0, 0), 3: (12, 0, 0)},
 13: {0: (21, 0.25, 0), 1: (5,

در قسمت اول از ما خواسته شده تا تابع مقدار یا همان ارزیابی سیاست را محاسبه کنیم 

In [96]:
#محاسبه تابع مقدار(ارزیابی سیاست)
def policy_evaluation(P,policy,threshold,dicount):
    value=np.zeros((noS,)) # مقداردهی اولیه تابع مقدار
    while True: # تا زمانی که همگرایی در تابع مقدار اتفاق نمی افتد حلقه را ادامه بده
        new_value=np.zeros((noS,)) # v مقداردهی اولیه تابع بروزرسانی  

        change=0
        for s in S: # برای تمام حالات
            v=0
            
            for a,action_prob in enumerate(policy[s]): #   برای تمامی اعمال و احتمال اعمال تحت سیاست مشخص در آن حالت
                next_state,probability,reward=P[s][a] # برای 4 مقداری که از بودن عامل در آن حالت و انجام آن عمل در محیط
                temp=probability*action_prob*(reward+discount*value[next_state]) # بروزرسانی تابع مقدار
                v+=temp

            change=max(change,np.abs(v-value[s])) # محاسبه اختلاف تابع مقدار جدید و قدیم
            new_value[s]=v # در صورتی که شرط خاتمه برقرار، قرار دادن تابع مقدار در مقدار جدید 

        if change < threshold:
              break

        value=new_value

    return value

In [97]:
random_policy = np.ones([noS, noA])/noA #  سیاست انتخاب عمل تصادفی

threshold = 0.0000000000001 # تعیین پارامتری با مقدار بسیار کم برای بررسی همگرایی
discount = 0.9  #مقداردهی اولیه ضریب تخفیف

random_policy_value=policy_evaluation(P,random_policy,threshold,discount)
print ('Value Function for policy: all actions equiprobable: discount = 0.9 :')
print (random_policy_value.reshape(8,8))

Value Function for policy: all actions equiprobable: discount = 0.9 :
[[7.54222620e-03 1.60728345e-03 2.07389049e-04 2.18052787e-05
  1.38822059e-06 9.77573206e-08 3.53131494e-08 1.11906874e-07]
 [1.17392285e-01 1.92170293e-02 1.85043865e-03 1.57066851e-04
  0.00000000e+00 2.16616887e-07 3.82811997e-07 1.73032866e-06]
 [1.94282242e+00 2.20786070e-01 1.33152018e-02 7.62988794e-04
  4.59961037e-05 3.15378069e-06 4.82328793e-06 2.85363508e-05]
 [3.22580645e+01 1.94973103e+00 0.00000000e+00 4.59804548e-05
  5.56983256e-06 5.03120381e-06 5.36743976e-05 4.72222936e-04]
 [1.94357604e+00 2.33303368e-01 0.00000000e+00 2.89122643e-06
  2.01148324e-06 2.70456125e-05 4.72134084e-04 7.84064074e-03]
 [1.17519015e-01 2.10049952e-02 0.00000000e+00 5.16416516e-07
  2.53030601e-07 1.63411762e-06 0.00000000e+00 1.30604171e-01]
 [7.12688470e-03 1.59475880e-03 9.61641988e-05 5.52006454e-06
  3.36304432e-07 1.18219245e-07 0.00000000e+00 2.05280294e+00]
 [4.59513896e-04 1.23223434e-04 1.31426937e-05 1.117560

در اینجا همانطور که میبینید خانه هایی که دیوار در ان قرار دارد تابع مقدار ان برابر صفر است و هر چه به هدف نزدیک میشویم این مقدار بیشتر میشود

In [98]:
random_policy = np.ones([64, 4])/4 #  سیاست انتخاب عمل تصادفی

threshold = 0.0000000000001 # تعیین پارامتری با مقدار بسیار کم برای بررسی همگرایی
discount = 0.1  #مقداردهی اولیه ضریب تخفیف

random_policy_value=policy_evaluation(P,random_policy,threshold,discount)
print ('Value Function for policy: all actions equiprobable: discount = 0.1: ')
print (random_policy_value.reshape(8,8))

Value Function for policy: all actions equiprobable: discount = 0.1: 
[[6.42202489e-06 1.59553483e-07 2.24700919e-09 2.50882003e-11
  1.58324838e-13 1.04773790e-15 2.91038305e-16 1.01281330e-14]
 [1.01452038e-03 1.89447334e-05 1.97696674e-07 1.74217281e-09
  0.00000000e+00 2.01398507e-14 3.99886630e-14 1.60781201e-12]
 [1.61283374e-01 2.01627972e-03 1.26827465e-05 7.92842841e-08
  4.98701527e-10 3.17668309e-12 4.79252776e-12 2.55632855e-10]
 [2.56410256e+01 1.61289753e-01 0.00000000e+00 4.98701353e-10
  6.27362169e-12 4.82151518e-12 5.08050784e-10 4.06394019e-08]
 [1.61283453e-01 2.02888269e-03 0.00000000e+00 3.14688077e-12
  1.64646190e-12 2.54045648e-10 4.06393920e-08 6.46090185e-06]
 [1.01452187e-03 1.91419126e-05 0.00000000e+00 5.91971911e-14
  2.07801349e-14 1.59774208e-12 0.00000000e+00 1.02720212e-03]
 [6.38189813e-06 1.59537940e-07 1.00350962e-09 6.27280679e-12
  3.92901711e-14 1.02445483e-14 0.00000000e+00 1.62291474e-01]
 [4.03997148e-08 1.25755544e-09 1.42199569e-11 1.285225

In [99]:
random_policy = np.ones([64, 4])/4 #  سیاست انتخاب عمل تصادفی

threshold = 0.0000000000001 # تعیین پارامتری با مقدار بسیار کم برای بررسی همگرایی
discount = 1  #مقداردهی اولیه ضریب تخفیف

random_policy_value=policy_evaluation(P,random_policy,threshold,discount)
print ('Value Function for policy: all actions equiprobable: discount = 1 ')
print (random_policy_value.reshape(8,8))

Value Function for policy: all actions equiprobable: discount = 1 
[[1.10922243e-02 2.61142035e-03 3.75549654e-04 4.41591005e-05
  3.17220145e-06 2.51719882e-07 9.33807478e-08 2.64213731e-07]
 [1.52679720e-01 2.77035312e-02 2.97766536e-03 2.83664652e-04
  0.00000000e+00 5.10216106e-07 8.84777657e-07 3.60561153e-06]
 [2.25140005e+00 2.84987694e-01 1.92799003e-02 1.23314531e-03
  8.33999907e-05 6.51674412e-06 9.94723419e-06 5.29351816e-05]
 [3.33333333e+01 2.26141962e+00 0.00000000e+00 8.33601036e-05
  1.13378017e-05 1.04104650e-05 9.88190437e-05 7.80474878e-04]
 [2.25261419e+00 3.02973214e-01 0.00000000e+00 5.91843768e-06
  4.23426765e-06 4.98938510e-05 7.80272123e-04 1.15553689e-02]
 [1.52906363e-01 3.05643930e-02 0.00000000e+00 1.18219406e-06
  5.98192172e-07 3.38476089e-06 0.00000000e+00 1.71769787e-01]
 [1.04168537e-02 2.58631803e-03 1.74957368e-04 1.12162812e-05
  7.69852207e-07 2.79370213e-07 0.00000000e+00 2.39322165e+00]
 [7.60124158e-04 2.24884560e-04 2.68262008e-05 2.55108491e

با تغییر اندازه مقدار ضریب تخفیف به این نتیجه رسیدیم که

اگر ضریب تخفیف را روی یک مقدار کوچک تنظیم کنیم یعنی نزدیک به صفر انگاه به پاداش های فوری اهمیت بیشتری میدهیم

اگر ضریب تخفیف را روی یک مقدار بزرگ تنظیم کنیم یعنی نزدیک به یک انگاه پاداش های اینده اهمیت بیشتری پیدا میکنند

# سوال دوم

در این قسمت از ما خواسته شده مقدار تکرار سیاست را به دست اوریم که شامل 3 بخش میشود محاسبه تابع مقدار یا همان ارزیابی سیاست 

محاسبه استخراج سیاست یا بهبود سیاست و در اخر الگوریتم تکرار سیاست است

In [100]:
#الگوریتم تکرار سیاست
def policy_iteration(P,discount,threshold):
   
    value=np.zeros((noS,)) #مقدار دهی اولیه تابع مقدار
    policy=np.ones([64, 4])/4 # مقدار دهی اولیه سیاست
    
    while True:
        #محاسبه تابع مقدار یا ارزیابی سیاست
        value=policy_evaluation(P,policy,threshold,discount) #فراخوانی تابع مقدار حالت 
        
        new_value=np.zeros((noS,)) #مقدار دهی اولیه 
        new_policy=np.zeros([noS,4]) #مقدار دهی اولیه
        
        #محاسبه استخراج سیاست یا بهبود سیاست
        policy_stable=True
        for s in S: #برای هر حالت  Q محاسبه
            
            old_action=policy[s]
            action_values = np.zeros(noA)
            for a in range(noA):   #برای هر عمل  Q محاسبه    
                    next_state,probability,reward = P[s][a] # MDPبدست آوردن دانش
                    action_values[a] += probability*(reward + discount*value[next_state]) # Q محاسبه و بروز رسانی مقادیر 
            max_total = np.amax(action_values)   #  انتخاب بیشترین مقدار تابع عمل وحالت - انتخاب سیاست حریصانه 
            best_a = np.argmax(action_values)

            new_policy[s][best_a]=1 #قرار دادن مقدار یک مقابل عملی که بهینه است

            new_value[s]=max_total  
            if (np.array_equal(old_action,new_policy[s])!=True):
                policy_stable=False
                    
        value=new_value
        
        if policy_stable: #مقدار برای مقادیری که دیوار است
            value[wall]=12,26,34,42,46,54,62
            return new_policy,value  #  برگرداندن مقدار سیاست بهینه
        else:
            policy=new_policy # جایگزین کردن سیاست قبلی با سیاست بعدی

In [101]:
best_policy,corr_value=policy_iteration(P,discount,threshold) # فراخوانی تابع تکرار سیاست 

In [102]:
best_policy

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],


In [73]:
corr_value  # چاپ تابع مقدار بهینه

array([[5.20833333e-01, 1.30208333e-01, 3.25520833e-02, 8.13802083e-03,
        2.03450521e-03, 5.08626302e-04, 5.08626302e-04, 2.03450521e-03],
       [2.08333333e+00, 5.20833333e-01, 1.30208333e-01, 3.25520833e-02,
        0.00000000e+00, 2.03450521e-03, 2.03450521e-03, 8.13802083e-03],
       [8.33333333e+00, 2.08333333e+00, 5.20833333e-01, 1.30208333e-01,
        3.25520833e-02, 8.13802083e-03, 8.13802083e-03, 3.25520833e-02],
       [3.33333333e+01, 8.33333333e+00, 0.00000000e+00, 3.25520833e-02,
        8.13802083e-03, 8.13802083e-03, 3.25520833e-02, 1.30208333e-01],
       [8.33333333e+00, 2.08333333e+00, 0.00000000e+00, 8.13802083e-03,
        8.13802083e-03, 3.25520833e-02, 1.30208333e-01, 5.20833333e-01],
       [2.08333333e+00, 5.20833333e-01, 0.00000000e+00, 2.03450521e-03,
        2.03450521e-03, 8.13802083e-03, 0.00000000e+00, 2.08333333e+00],
       [5.20833333e-01, 1.30208333e-01, 3.25520833e-02, 8.13802083e-03,
        2.03450521e-03, 2.03450521e-03, 0.00000000e+00, 8.

In [103]:
best_policy

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],


In [104]:
#را برای بهتر دیده شدن به صورت زیر هم میشود قرار داد  best_policy 
optimal_policy_function=np.zeros([64])

In [105]:
for i in range(64):
    for j in range(4):
        if (best_policy[i][j]==1):
            optimal_policy_function[i]=j

In [106]:
optimal_policy_function

array([0., 0., 0., 0., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 3., 3., 3., 3., 0., 0., 0., 3., 0., 1., 1., 0., 0., 0., 1., 1.,
       0., 1., 2., 2., 2., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 3.,
       3., 3., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0.])

In [108]:
map_act = {0:'^', 1:'v', 2:'<', 3:'>'}                                              # جهت مشخص تر شدن نمایش
optimal_policy = (np.array([map_act[x] for x in optimal_policy_function])).reshape([8,-1])  # چاپ سیاست بهینه

print("optimal_policy=\n",optimal_policy)


optimal_policy=
 [['^' '^' '^' '^' '>' '^' '^' '^']
 ['^' '^' '^' '^' '^' '^' '^' '^']
 ['^' '^' '>' '>' '>' '>' '^' '^']
 ['^' '>' '^' 'v' 'v' '^' '^' '^']
 ['v' 'v' '^' 'v' '<' '<' '<' '^']
 ['v' 'v' '^' '^' 'v' 'v' '^' '^']
 ['v' 'v' '>' '>' '>' 'v' '^' '^']
 ['v' 'v' 'v' 'v' 'v' 'v' '^' '^']]


# سوال سوم

In [78]:
#الگوریتم تکرار مقدار

def value_iteration(P,discount,threshold):
    value=np.zeros((noS,)) #مقداردهی اولیه تابع مقدار
    while True:
        new_policy=np.zeros([noS,4]) # مقدار دهی اولیه سیاست
        change=0
        for s in S: # محاسبه برای تمامی حالات
            v=value[s]
            action_values = np.zeros(noA)
            for a in range(4):   #محاسبه هر عمل
                next_state,probability,reward = P[s][a] # MDPبدست آوردن دانش 
                action_values[a] += probability*(reward + discount*value[next_state]) #محاسبه و بروز رسانی مقادیر 
            max_total = np.amax(action_values)   # انتخاب بیشترین مقدار پاداش ---انتخاب حریصانه
            best_a = np.argmax(action_values)

            value[s]=max_total
            new_policy[s][best_a]=1 #قرار دادن مقدار یک مقابل عملی که بهینه است

            change=max(change,np.abs(v-value[s])) #محاسبه اختلاف تابع مقدار جدید و قدیم
            
        if change < threshold:
              break
    return new_policy,value.reshape(8,8)

In [79]:
best_policy,corr_value=value_iteration(P,discount,threshold)

In [80]:
corr_value

array([[5.20833333e-01, 1.30208333e-01, 3.25520833e-02, 8.13802083e-03,
        2.03450521e-03, 5.08626302e-04, 5.08626302e-04, 2.03450521e-03],
       [2.08333333e+00, 5.20833333e-01, 1.30208333e-01, 3.25520833e-02,
        0.00000000e+00, 2.03450521e-03, 2.03450521e-03, 8.13802083e-03],
       [8.33333333e+00, 2.08333333e+00, 5.20833333e-01, 1.30208333e-01,
        3.25520833e-02, 8.13802083e-03, 8.13802083e-03, 3.25520833e-02],
       [3.33333333e+01, 8.33333333e+00, 0.00000000e+00, 3.25520833e-02,
        8.13802083e-03, 8.13802083e-03, 3.25520833e-02, 1.30208333e-01],
       [8.33333333e+00, 2.08333333e+00, 0.00000000e+00, 8.13802083e-03,
        8.13802083e-03, 3.25520833e-02, 1.30208333e-01, 5.20833333e-01],
       [2.08333333e+00, 5.20833333e-01, 0.00000000e+00, 2.03450521e-03,
        2.03450521e-03, 8.13802083e-03, 0.00000000e+00, 2.08333333e+00],
       [5.20833333e-01, 1.30208333e-01, 3.25520833e-02, 8.13802083e-03,
        2.03450521e-03, 2.03450521e-03, 0.00000000e+00, 8.